- hosts: anode
  
  vars:
    listvar1:
    - 'Kuber'
    - 'OpnShft'
    - 'Mesos'
  tasks:
    - shell: echo "nested test a={{ item[0] }} b={{ item[1] }} c={{ item[2] }}"
      with_nested:
        - "{{ listvar1 }}"
        - [ 'red', 'blue', 'green']
        - [ 'up', 'down', 'side']
