- hosts: anode
  remote_user: ansible
  become: true
  vars:
    dict1:
      msg_var: hiWelcome
      abc: alphabets
      lists: items
  tasks:  
    - name: DebugMessage
      debug:
        msg: "{{ dict1 }}"
