- hosts: anode
  remote_user: ansible
  become: true
  vars:
    msg_var: HelloWorld
    abc: abc
  tasks:  
  - name: HelloWorld
    debug:
      msg: "{{ msg_var }}"
  - name: secondHelloWorld
    debug:
      msg: "{{ abc }}"
